<?php
/**
 * db/seed.php
 *
 * One-time data loader. Transcribes the original hardcoded JS arrays
 * (teachers, timetable, students) into the MySQL tables created by
 * schema.sql. Passwords are hashed with password_hash() here, since
 * hashes must be generated by PHP itself.
 *
 * Run once from the command line on your server:
 *   php db/seed.php
 *
 * Safe to re-run: uses INSERT ... ON DUPLICATE KEY UPDATE / ignores
 * existing rows where sensible.
 */

require_once __DIR__ . '/../config.php';

// ---------------------------------------------------------------
// 1. Teachers  (id, name, department, password)
//    Demo password for every teacher = their own Teacher ID,
//    matching the original app's demo credentials.
// ---------------------------------------------------------------
$teachers = [
  ['T001',  'DR.S.MALATHI',            'Computer Science', 'T001'],
  ['T002',  'DR.A.JOSHI',              'Mathematics',       'T002'],
  ['T003',  'DR.T.KALAICHELVI',        'Physics',           'T003'],
  ['T004',  'DR.K.JAYASHREE',          'Physics',           'T004'],
  ['T005',  'DR.S.CHAKARAVARTHI',      'Physics',           'T005'],
  ['T006',  'DR.W.GRACYTHERESA',       'Physics',           'T006'],
  ['T007',  'DR.N.R.RAM MOHAN',        'Physics',           'T007'],
  ['T008',  'DR.N.SIVAKUMAR',          'Physics',           'T008'],
  ['T009',  'DR.C.GNANAPRAKASAM',      'Physics',           'T009'],
  ['T0010', 'DR.C. BHARANIDHARAN',     'Physics',           'T0010'],
  ['T0011', 'DR.M.SMAHARAJAN',         'Physics',           'T0011'],
  ['T0012', 'DR.E.BHUVANESWARI',       'Physics',           'T0012'],
  ['T0013', 'DR.T.VEERAMANI',          'Physics',           'T0013'],
  ['T0014', 'DR.S.LEELAVATHY',         'Physics',           'T0014'],
  ['T0015', 'MRS.S.VIMALA',            'Physics',           'T0015'],
  ['T0016', 'DR.C.VIVEK',              'Physics',           'T0016'],
  ['T0017', 'DR.T.SELVABANUPRIYA',     'Physics',           'T0017'],
  ['T0018', 'DR.V.MAHAVAISHNAVI',      'Physics',           'T0018'],
  ['T0019', 'DR.M.VIDHYASREE',         'Physics',           'T0019'],
  ['T0020', 'DR.T.DR.DS.SHAJI',        'Physics',           'T0020'],
  ['T0021', 'MR.M. SADHASIVAM',        'Physics',           'T0021'],
  ['T0022', 'MRS.T.KAVITHA',           'Physics',           'T0022'],
  ['T0023', 'DR.S.SRINIDHI',           'Physics',           'T0023'],
  ['T0024', 'DR.V.RATHINAPRIYA',       'Physics',           'T0024'],
  ['T0025', 'DR.S.RAVEENA',            'Physics',           'T0025'],
  ['T0026', 'MRS.R.PRIYA',             'Physics',           'T0026'],
  ['T0027', 'MRS.A.BABISHA',           'Physics',           'T0027'],
  ['T0028', 'MRS.C M HILDA JERLIN',    'Physics',           'T0028'],
  ['T0029', 'MRS.B.BALA ABIRAMI',      'Physics',           'T0029'],
  ['T0030', 'MR.M.VETRISELVAN',        'Physics',           'T0030'],
  ['T0031', 'MRS.R.VIDHYAMUTHULAKSHMI','Physics',           'T0031'],
  ['T0032', 'MRS.V REKHA',             'Physics',           'T0032'],
  ['T0033', 'MRS.S.SWATHI',            'Physics',           'T0033'],
  ['T0034', 'MRS.J.ANITHA',            'Physics',           'T0034'],
  ['T0035', 'MRS.C.GOMATHI',           'Physics',           'T0035'],
  ['T0036', 'MR.P.KALIAPPAN',          'Physics',           'T00136'],
  ['T0037', 'MRS.P.MISBA MARY BAI',    'Physics',           'T0037'],
];

// ---------------------------------------------------------------
// 2. Timetable (day, start, end, class, subject, teacher_id)
// ---------------------------------------------------------------
$timetable = [
  ['Monday',    '09:00', '10:00', 'CS-A', 'Data Structures', 'T002'],
  ['Monday',    '10:00', '11:00', 'CS-B', 'Algorithms',      'T001'],
  ['Monday',    '11:30', '12:30', 'CS-A', 'DBMS',            'T001'],
  ['Monday',    '14:00', '15:00', 'CS-B', 'OS',              'T001'],
  ['Tuesday',   '09:00', '10:00', 'CS-B', 'Data Structures', 'T001'],
  ['Tuesday',   '10:00', '11:00', 'CS-A', 'Algorithms',      'T001'],
  ['Tuesday',   '11:30', '12:30', 'CS-C', 'DBMS',            'T001'],
  ['Tuesday',   '14:00', '15:00', 'CS-B', 'OS',              'T001'],
  ['Wednesday', '09:00', '10:00', 'CS-A', 'Data Structures', 'T001'],
  ['Wednesday', '10:00', '11:00', 'CS-C', 'Algorithms',      'T001'],
  ['Thursday',  '09:00', '10:00', 'CS-B', 'DBMS',            'T001'],
  ['Thursday',  '10:00', '11:00', 'CS-A', 'OS',              'T001'],
  ['Thursday',  '11:30', '12:30', 'CS-C', 'Data Structures', 'T001'],
  ['Friday',    '09:00', '10:00', 'CS-A', 'Algorithms',      'T001'],
  ['Friday',    '10:00', '11:00', 'CS-B', 'DBMS',            'T001'],
  ['Friday',    '11:30', '12:30', 'CS-C', 'OS',              'T001'],
  ['Saturday',  '09:00', '10:00', 'CS-A', 'DBMS',            'T001'],
  ['Saturday',  '10:00', '11:00', 'CS-B', 'Algorithms',      'T001'],
];

// ---------------------------------------------------------------
// 3. Students (roll_no, name, class_name)
//    NOTE: in the original app this list is keyed "IV-A" while the
//    timetable above uses "CS-A" / "CS-B" / "CS-C" — that mismatch
//    already existed in the source file (Mark Attendance would show
//    an empty roster for CS-* classes). Seeded as-is; rename
//    class_name below, or add more rows, to match your real classes.
// ---------------------------------------------------------------
$students = [
  ['2114242430022', 'AKSHAYA G',            'IV-A'],
  ['2114242430045', 'BENCY SANDRA M',       'IV-A'],
  ['2114242430086', 'DHONA NANCY A',        'IV-A'],
  ['2114242430156', 'HONEY BRITTNEY I',     'IV-A'],
  ['2114242430176', 'JEEVAJOTHI K',         'IV-A'],
  ['2114242430190', 'KANISHKA V',           'IV-A'],
  ['2114242430219', 'KRITHIKA S',           'IV-A'],
  ['2114242430259', 'MERCY.M',              'IV-A'],
  ['2114242430287', 'S.NABEEHA',            'IV-A'],
  ['2114242430326', 'PRAKIMA M',            'IV-A'],
  ['2114242430358', 'RENITTA J',            'IV-A'],
  ['2114242430382', 'SANJANA C',            'IV-A'],
  ['2114242430436', 'SWASTHIKA S',          'IV-A'],
  ['2114242430449', 'THAMIZHSELVI A S',     'IV-A'],
  ['2114242430484', 'VISHALI A',            'IV-A'],
  ['2114242430504', 'YUVATHI V',            'IV-A'],
  ['2114242430001', 'Qasim Khan',           'IV-A'],
  ['2114242430018', 'AJITH KUMAR P',        'IV-A'],
  ['2114242430037', 'ARUN NAGARAJ G',       'IV-A'],
  ['2114242430052', 'CHARISH C',            'IV-A'],
  ['2114242430062', 'DEEPAN M',             'IV-A'],
  ['2114242430083', 'DHAYANITHI J',         'IV-A'],
  ['2114242430108', 'GAUTHAMKUMAR U',       'IV-A'],
  ['2114242430129', 'HARI PREETH S K',      'IV-A'],
  ['2114242430148', 'HARSITH J',            'IV-A'],
  ['2114242430183', 'JOE PRINCE A',         'IV-A'],
  ['2114242430294', 'NAVEENKUMAR S',        'IV-A'],
  ['2114242430154', 'HEMANTHRAJAN T K',     'IV-A'],
  ['2114242430135', 'HARIKIRAN A',          'IV-A'],
  ['2114242430123', 'HAARISH RAGAVENDER',   'IV-A'],
  ['2114242430099', 'ESAKKI SURYA E',       'IV-A'],
  ['2114242430070', 'DHANUSH M',            'IV-A'],
  ['2114242430378', 'SAMUEL A',             'IV-A'],
  ['2114242430346', 'RAJANBALAJI R',        'IV-A'],
  ['2114242430417', 'SOMINENI SAI KRISHNA', 'IV-A'],
  ['2114242430414', 'SIVAMURUGAN P',        'IV-A'],
  ['2114242430444', 'TARUN PADMANABHAN',    'IV-A'],
  ['2114242430483', 'VISHAL M',             'IV-A'],
  ['A01',            'Aarav Singh',         'IV-A'],
];

// ---------------------------------------------------------------
// Insert
// ---------------------------------------------------------------
$pdo->beginTransaction();

try {
    $stmt = $pdo->prepare(
        'INSERT INTO teachers (id, name, department, password_hash) VALUES (?, ?, ?, ?)
         ON DUPLICATE KEY UPDATE name = VALUES(name), department = VALUES(department)'
    );
    foreach ($teachers as [$id, $name, $dept, $plainPassword]) {
        $stmt->execute([$id, $name, $dept, password_hash($plainPassword, PASSWORD_DEFAULT)]);
    }
    echo 'Seeded ' . count($teachers) . " teachers.\n";

    $pdo->exec('DELETE FROM timetable'); // safe to fully rebuild
    $stmt = $pdo->prepare(
        'INSERT INTO timetable (teacher_id, day_of_week, start_time, end_time, class_name, subject)
         VALUES (?, ?, ?, ?, ?, ?)'
    );
    foreach ($timetable as [$day, $start, $end, $class, $subject, $teacherId]) {
        $stmt->execute([$teacherId, $day, $start, $end, $class, $subject]);
    }
    echo 'Seeded ' . count($timetable) . " timetable rows.\n";

    $stmt = $pdo->prepare(
        'INSERT INTO students (roll_no, name, class_name) VALUES (?, ?, ?)
         ON DUPLICATE KEY UPDATE name = VALUES(name), class_name = VALUES(class_name)'
    );
    foreach ($students as [$roll, $name, $class]) {
        $stmt->execute([$roll, $name, $class]);
    }
    echo 'Seeded ' . count($students) . " students.\n";

    $pdo->commit();
    echo "Done. Demo login: any Teacher ID (e.g. T001) with password equal to the ID (e.g. T001).\n";
} catch (Throwable $e) {
    $pdo->rollBack();
    echo 'Seed failed: ' . $e->getMessage() . "\n";
    exit(1);
}
